@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(merchant_context, "Merchant/Callbacks Context") {
  Container(callbacks_service, "Callbacks Service", "Java, Spring Boot", "Управление коллбэками\nМерчанты")
  ContainerDb(callbacks_db, "Callbacks DB", "PostgreSQL", "Хранение эндпоинтов и попыток")
  Container(kafka, "Kafka", "Kafka", "События платежей")

  Container_Boundary(internal, "Внутренние компоненты") {
    Container(orchestrator, "Callback Orchestrator", "Java", "Управление отправкой коллбэков")
    Container(registry, "Merchant Registry", "Java", "Регистрация мерчантов")
    Container(retry, "Retry Manager", "Java", "Стратегии повторных отправок")
  }
}

Rel(callbacks_service, callbacks_db, "Синхронный", "JDBC")
Rel(callbacks_service, kafka, "Асинхронный")
Rel(callbacks_service, orchestrator, "Внутренний вызов", "Синхронный")
Rel(callbacks_service, registry, "Внутренний вызов", "Синхронный")
Rel(callbacks_service, retry, "Внутренний вызов", "Синхронный")


@enduml