@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(notifications_context, "Notifications Context") {
  System(notifications_service, "Notifications Service", "Java, Spring Boot", "Управление уведомлениями\nШаблоны")
  ContainerDb_Ext(notifications_db, "Notifications DB", "Cassandra", "Хранение шаблонов и статусов")
  System_Ext(kafka, "Kafka", "Kafka", "События для критичных уведомлений")

  Container_Boundary(internal, "Внутренние компоненты") {
    Container(dispatcher, "Notification Dispatcher", "Java", "Маршрутизация уведомлений")
    Container(templates, "Template Manager", "Java", "Управление шаблонами")
    Container(channels, "Channel Adapters", "Java", "Интеграция с провайдерами")
  }
}

Rel(notifications_service, notifications_db, "JDBC\nСинхронный")
Rel(notifications_service, dispatcher, "Внутренний вызов", "Синхронный")
Rel(notifications_service, templates, "Внутренний вызов", "Синхронный")
Rel(notifications_service, channels, "Внутренний вызов", "Синхронный")
Rel(kafka, notifications_service, "События платежей\nKafka\nАсинхронный")

@enduml