@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(payments_context, "Payments Context") {
  Container(payments_service, "Payments Service", "Java, Spring Boot", "Оркестрация платежей")
  Container(kafka, "Kafka", "Kafka", "События платежей")

  Container_Boundary(internal, "Внутренние компоненты") {
    Container(orchestrator, "Payment Orchestrator", "Java", "Управление жизненным циклом платежа")
    Container(reservation, "Reservation Processor", "Java", "Резервирование средств")
    Container(settlement, "Settlement Processor", "Java", "Списание средств")
    ContainerDb_Ext(payments_db, "Payments DB", "PostgreSQL", "Хранение платежей")
  }
}

Rel(orchestrator, payments_db, "JDBC\nСинхронная", "Сохранение платежа + Запись в Outbox")
Rel_R(payments_service, kafka, "payment.completed\nKafka\nАсинхронная")
Rel(payments_service, orchestrator, "Внутренний вызов", "Синхронная")
Rel(orchestrator, reservation, "Управление", "Синхронная")
Rel(orchestrator, settlement, "Управление", "Синхронная")

@enduml