@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Клиент", "Пользователь мобильного/веб-банка")
System_Ext(merchant, "Merchant/VISA", "Внешний продавец/сервис")

System_Boundary(system, "Платёжная платформа") {
  Container(kong, "Kong API Gateway", "JWT, Rate Limiting, LB", "Аутентификация, маршрутизация, балансировка нагрузок")
  Container(core_banking, "Core Banking (Legacy)", "Java Legacy", "Бухгалтерский учёт")

  System_Boundary(payments_boundary, "Payments Context") {
    Container(payments, "Payments Service", "Spring Boot", "Оркестрация платежей\nUUIDv7 как глобальный ID")
    ContainerDb(payments_db, "Payments DB", "PostgreSQL", "Хранение платежей\n(статусы, outbox)")
    Container(outbox_worker, "Outbox Worker", "Scheduler", "Отправка событий из outbox в Kafka")
  }

  System_Boundary(wallet_boundary, "Wallet Context") {
    Container(wallet, "Wallet Service", "Spring Boot", "Управление кошельками\nРезервирование, балансы")
    ContainerDb(wallet_db, "Wallet DB", "PostgreSQL", "Хранение балансов и блокировок")
  }

  System_Boundary(fraud_boundary, "Anti-Fraud Context") {
    Container(fraud, "Anti-Fraud Service", "Kotlin", "Онлайн-проверка\nСкоринг рисков")
    ContainerDb(fraud_db, "Fraud Model DB", "Cassandra", "Хранение скоринговых моделей")
  }

  System_Boundary(notifications_boundary, "Notifications Context") {
    Container(notifications, "Notifications Service", "Spring Boot", "Управление уведомлениями")
  }

  System_Boundary(callbacks_boundary, "Callbacks Context") {
    Container(callbacks, "Callbacks Service", "Spring Boot", "Управление коллбэками мерчантам")
    ContainerDb(callbacks_db, "Callbacks DB", "PostgreSQL", "Хранение эндпоинтов и попыток")
  }

  System_Boundary(integration, "Anti-Corruption Layer (ACL)") {
    Container(adapter, "Core Integration (Adapter)", "Spring Boot", "\nПреобразование json → xml")
  }

   System_Boundary(Kafka_cont, "Событийная шина") {
  Container(kafka, "Kafka", "Kafka", "(payment.*)\nКритические события")
    }
}

' Основные потоки
Rel(customer, kong, "Синхронный", "REST")
Rel_R(kong, payments, "Синхронный", "REST")

' Синхронные связи внутри Payments
Rel(payments, wallet, "резервирование средств", "gRPC")
Rel(payments, fraud, "проверка риска", "gRPC")
Rel(payments, payments_db, "Синхронный", "JDBC")
Rel(outbox_worker, payments_db, "Чтение из outbox\nСинхронный")

' Асинхронные связи через Kafka
Rel(outbox_worker, kafka, "payment.created", "REST")
Rel(kafka, wallet, "payment.completed\npayment.failed", "Async")
Rel(kafka, adapter, "payment.completed\npayment.failed", "Async")
Rel(kafka, notifications, "payment.completed\npayment.failed", "Async")
Rel(kafka, callbacks, "payment.completed\npayment.failed", "Async")
Rel(kafka, payments, "payment.failed\npayment.completed", "Async")

' Дополнительные связи
Rel(adapter, core_banking, "Синхронный преобразованный запрос", "SOAP")
Rel(wallet, wallet_db, "Синхронный", "JDBC")
Rel(notifications, customer, "User Notification", "Push/SMS/Email")
Rel(callbacks, merchant, "Merchant Notification", "Webhook\nREST")
Rel(callbacks, callbacks_db, "Синхронный", "JDBC")
Rel(fraud, fraud_db, "Синхронный", "CQL")

@enduml